---
title: BD2HAN Rat p27kip / Cdkn1b / Utf1
output:
  html_document: default
fig_width: 14
fig_height: 12
---

Data is generated by Nextflow 'RNAseq_kallisto'
```{r message = FALSE, warning = FALSE}
##working dir is location of Rmd, here BM/deconv
load("../data/BD2HAN_2_RNAseqR/RData/BD2HAN_2.DE_ready.RData")
mf <- ("../data/metadata/BDII_Han_Rat2_metadata.TISSUE_ARM_immune_090321.csv")
metadata <- readr::read_csv(mf)
ls()
```
Parse genes of interest and plot
```{r message = FALSE, warning = FALSE}
library(tidyverse)
tpm_tb_u <- tpm_tb %>% dplyr::filter(external_gene_name %in% c("Cdkn1b", "Utf1"))
tpm_tb_ul <- tidyr::pivot_longer(data = tpm_tb_u,
                                 cols = !c("ensembl_gene_id",
                                           "external_gene_name"),
                                 names_to = "sample",
                                 values_to = "TPM") %>%
             dplyr::mutate(log2TPM = log2(TPM))
vars_sel <- c("IMMUNE", "CARE_ARM", "TUMOUR_TYPE", "TISSUE", "TISSUE_ARM")
tpm_df_ulm <- metadata %>% dplyr::select(sample, !!vars_sel) %>%
              dplyr::left_join(tpm_tb_ul, ., by = "sample") %>%
              as.data.frame()

plot_list <- lapply(vars_sel, function(coln){
  coln <- sym(coln)
  ggp <- ggplot2::ggplot(data = tpm_df_ulm,
                         aes(x = !!coln,
                             y = log2TPM,
                             colour = .data[[coln]])) +
         ggplot2::geom_violin() +
         ggplot2::geom_jitter(aes(x = .data[[coln]]),
                              position = position_jitter()) +
         ggplot2::labs(y = "log2TPM",
                       title = paste0("Expression per ", coln, " group per gene"),
                       subtitle = tag) +
         ggplot2::facet_wrap(~external_gene_name) +
         ggplot2::theme(axis.title.x = element_blank(),
                        axis.text.x = element_blank(),
                        axis.ticks.x = element_blank(),
                        panel.grid = element_blank(),
                        strip.text.x = element_text(size = 7,
                                                    face = "bold"))
  return(ggp)
})
names(plot_list) <- vars_sel
```
******
\newpage

## Generate Plots
```{r echo = FALSE, message = FALSE, warning = FALSE}
lapply(plot_list, function(f){
  f
})
```

******
